CREATE TABLE IF NOT EXISTS USER (
    USER        INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME    VARCHAR(255) NOT NULL,
    PASSWORD   	VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEVICE (
    DEVICE      INT AUTO_INCREMENT PRIMARY KEY, 
    CODE        INT,            
    NAME 		VARCHAR(255), 
    
    LASTPING 	DATETIME,
    CONNECTKEY	VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TYPE (
	TYPE 		INT AUTO_INCREMENT PRIMARY KEY,
	CODE 		INT,
	NAME 		VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MAKER (
	MAKER 		INT AUTO_INCREMENT PRIMARY KEY,
	CODE 		INT,
	NAME 		VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT (
	PRODUCT 	INT AUTO_INCREMENT PRIMARY KEY,
    CODE 		INT,
    NAME		VARCHAR(255) NOT NULL,
    
    TYPE		INT NOT NULL,
    MAKER		INT NOT NULL,
    PRICE 		FLOAT,
    DISCOUNT 	FLOAT,
    FINALPRICE	FLOAT,
    NOTES 		VARCHAR(255)
	-- FOREIGN KEY (TYPE) REFERENCES TYPE(TYPE),
    -- FOREIGN KEY (MAKER) REFERENCES MAKER(MAKER)
);

CREATE TABLE IF NOT EXISTS CAROUSEL (
	CAROUSEL 		INT AUTO_INCREMENT PRIMARY KEY,
    CODE 			INT,
    NAME			VARCHAR(255) NOT NULL,
    
    DEVICE			INT,
    NOTES			VARCHAR(255),
    AUTOPLAYWAIT 	INT,
    SPEED	 		INT,
    GAMECOUNT		INT
    
	-- FOREIGN KEY (DEVICE) REFERENCES DEVICE(DEVICE)
);

CREATE TABLE IF NOT EXISTS PROMO (
	PROMO	 	INT AUTO_INCREMENT PRIMARY KEY,
    CODE 		INT,
    
    PRODUCT		INT,
    TYPE		INT,
    MAKER		INT,
    
    DISCOUNT	FLOAT,
    CHANCE	 	FLOAT,
    DAYSTOLIVE	INT
);

CREATE TABLE IF NOT EXISTS MINIGAME (
	MINIGAME 		INT AUTO_INCREMENT PRIMARY KEY,
    CAROUSEL		INT NOT NULL,
    
    REVOLUTIONS		INT,
    SPINDURATION 	INT,
    ONSTOPTIME		INT,
    INACTIVITYTIME 	INT
    
    -- FOREIGN KEY (CAROUSEL) REFERENCES CAROUSEL(CAROUSEL)
);

CREATE TABLE IF NOT EXISTS PRODUCTLINES (
	PRODUCTLINES 	INT AUTO_INCREMENT PRIMARY KEY,
    CAROUSEL		INT NOT NULL,
    PRODUCT			INT NOT NULL,
    QUEUE 			INT

	-- FOREIGN KEY (CAROUSEL) REFERENCES CAROUSEL(CAROUSEL),
    -- FOREIGN KEY (PRODUCT) REFERENCES PRODUCT(PRODUCT)
);

CREATE TABLE IF NOT EXISTS BACKSWIPES (
	BACKSWIPES 		INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTLINES	INT NOT NULL,
    SWIPEDATE		DATETIME

	-- FOREIGN KEY (PRODUCTLINES) REFERENCES PRODUCTLINES(PRODUCTLINES)
);

CREATE TABLE IF NOT EXISTS PROMOLINES (
	PROMOLINES 		INT AUTO_INCREMENT PRIMARY KEY,
    PROMO			INT NOT NULL,
    MINIGAME		INT NOT NULL

	-- FOREIGN KEY (PROMO) REFERENCES PROMO(PROMO),
    -- FOREIGN KEY (MINIGAME) REFERENCES MINIGAME(MINIGAME)
);

CREATE TABLE IF NOT EXISTS ISSUEDPROMO (
	ISSUEDPROMO	INT AUTO_INCREMENT PRIMARY KEY,
    
    REDEEMCODE 	INT NOT NULL,
    PROMO		INT NOT NULL,
    DEVICE		INT,
    CAROUSEL	INT,
    MINIGAME	INT,
    REDEEMED	BOOLEAN,
    ISSUEDATE	DATETIME
    
    -- FOREIGN KEY (PROMO) REFERENCES PROMO(PROMO)
);


