DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetCarouselProducts`(IN p_connectkey VARCHAR(255))
BEGIN
    SELECT 
        PL.PRODUCT, 
        PL.QUEUE,
        PR.NAME,
        PR.PRICE,
        PR.DISCOUNT,
        PR.FINALPRICE
    FROM 
        PRODUCTLINES PL
        INNER JOIN PRODUCT PR ON PL.PRODUCT = PR.PRODUCT
        INNER JOIN CAROUSEL C ON C.CAROUSEL = PL.CAROUSEL
        INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE
    WHERE 
        D.CONNECTKEY = p_connectkey
    ORDER BY 
        PL.QUEUE;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetCarouselSettings`(IN p_connectkey VARCHAR(255))
BEGIN
    SELECT AUTOPLAYWAIT,SPEED,GAMECOUNT,STATE
    FROM CAROUSEL C
    INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE
    WHERE D.CONNECTKEY = p_connectkey;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetFilteredProducts`(
    IN input_type VARCHAR(100),
    IN input_maker VARCHAR(100)
)
BEGIN
    SELECT 
        P.PRODUCT AS ID,
        P.CODE,
        P.NAME,
        T.NAME AS TYPE,
        M.NAME AS MAKER,
        P.PRICE,
        P.DISCOUNT,
        P.FINALPRICE,
        P.NOTES,
        C.CODE AS CAROUSELCODE,
        C.NAME AS CAROUSELNAME,
        PRO.CODE AS PROMOCODE,
        PRO.DISCOUNT as PROMODISCOUNT
    FROM 
        PRODUCT P
    LEFT JOIN 
        MAKER M ON M.MAKER = P.MAKER
    LEFT JOIN 
        TYPE T ON T.TYPE = P.TYPE
	LEFT JOIN
		PRODUCTLINES PR ON PR.PRODUCT = P.PRODUCT
	LEFT JOIN 
		CAROUSEL C ON C.CAROUSEL = PR.CAROUSEL
	LEFT JOIN
		PROMO PRO ON PRO.PRODUCT = P.PRODUCT
    WHERE 
        (input_type IS NULL OR T.NAME = input_type)
        AND (input_maker IS NULL OR M.NAME = input_maker)
        group by p.code;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetMakers`()
BEGIN
SELECT MAKER AS ID, CODE, NAME FROM MAKER;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetMinigamePromos`(IN p_connectkey INT)
BEGIN
SELECT PROMO.PROMO,PRODUCT.NAME as PRODUCTNAME,PRODUCT.PRODUCT as PRODUCT,TYPE.NAME as TYPENAME,MAKER.NAME as MAKERNAME,PROMO.DISCOUNT,PROMO.DAYSTOLIVE,PROMO.CHANCE
FROM PROMO
LEFT JOIN PRODUCT ON PRODUCT.PRODUCT = PROMO.PRODUCT
LEFT JOIN PROMOLINES ON PROMOLINES.PROMO = PROMO.PROMO
LEFT JOIN MINIGAME ON MINIGAME.MINIGAME = PROMOLINES.MINIGAME
LEFT JOIN CAROUSEL ON CAROUSEL.CAROUSEL = MINIGAME.CAROUSEL
LEFT JOIN DEVICE ON DEVICE.DEVICE = CAROUSEL.DEVICE
LEFT JOIN MAKER ON MAKER.MAKER = PROMO.MAKER
LEFT JOIN TYPE ON TYPE.TYPE = PROMO.TYPE
WHERE CONNECTKEY = p_connectkey;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetMinigameSettings`(IN p_connectkey INT)
BEGIN
    SELECT 
        m.revolutions,
        m.spinduration,
        m.onstoptime,
        m.inactivitytime
    FROM minigame m
    INNER JOIN carousel c ON c.carousel = m.carousel
    INNER JOIN device d ON d.device = c.device
    WHERE d.connectkey = p_connectkey;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetProducts`()
BEGIN
SELECT PRODUCT AS ID,P.CODE,P.NAME,T.NAME AS TYPE,M.NAME AS MAKER,PRICE,DISCOUNT,FINALPRICE,NOTES 
FROM PRODUCT P
INNER JOIN MAKER M ON M.MAKER = P.MAKER
INNER JOIN TYPE T ON T.TYPE = P.TYPE;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetPromoData`(IN p_redeemcode INT)
BEGIN
SELECT REDEEMCODE,
	DEVICE,
	CAROUSEL,
	MINIGAME,
	REDEEMED,
	ISSUEDATE,
	P.CODE,
	T.NAME AS TYPE,
	M.NAME AS MAKER,
    PR.NAME AS PRODUCT,
	P.DISCOUNT AS DISCOUNT,
	CHANCE,
	DAYSTOLIVE 
FROM 
	ISSUEDPROMO I
INNER JOIN 
	PROMO P ON I.PROMO = P.PROMO
LEFT JOIN 
	MAKER M ON M.MAKER = P.MAKER
LEFT JOIN 
	TYPE T ON T.TYPE = P.TYPE
LEFT JOIN 
	PRODUCT PR ON PR.PRODUCT = P.PRODUCT
WHERE REDEEMCODE = p_redeemcode;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetPromoStatus`(IN codetocheck VARCHAR(255))
BEGIN
    SELECT 
        CASE 
            WHEN NOT EXISTS (
                SELECT 1
                FROM ISSUEDPROMO
                WHERE REDEEMCODE = codetocheck
            ) THEN 0  -- Code does not exist

            WHEN EXISTS (
                SELECT 1
                FROM ISSUEDPROMO
                INNER JOIN PROMO ON ISSUEDPROMO.PROMO = PROMO.PROMO
                WHERE REDEEMCODE = codetocheck
                  AND REDEEMED = TRUE
            ) THEN 3  -- Code is redeemed

            WHEN EXISTS (
                SELECT 1
                FROM ISSUEDPROMO
                INNER JOIN PROMO ON ISSUEDPROMO.PROMO = PROMO.PROMO
                WHERE REDEEMCODE = codetocheck
                  AND ISSUEDATE >= DATE_SUB(NOW(), INTERVAL PROMO.DAYSTOLIVE DAY)
                  AND REDEEMED = FALSE
            ) THEN 1  -- Code is valid and not redeemed

            ELSE 2  -- Code is expired
        END AS status;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetTypes`()
BEGIN
SELECT TYPE AS ID,CODE,NAME FROM TYPE;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `InsertIssuedPromo`(IN p_connectkey INT, p_redeemcode INT,  p_promo  INT)
BEGIN
INSERT INTO ISSUEDPROMO (
    REDEEMCODE,
    PROMO,
    DEVICE,
    CAROUSEL,
    MINIGAME,
    REDEEMED,
    ISSUEDATE
)
VALUES (
    p_redeemcode, 
    p_promo,
    (SELECT DEVICE FROM DEVICE WHERE CONNECTKEY = p_connectkey),
    (SELECT C.CAROUSEL FROM CAROUSEL C INNER JOIN DEVICE D ON D.DEVICE = C.CAROUSEL WHERE D.CONNECTKEY = p_connectkey),
    (SELECT M.MINIGAME FROM MINIGAME M INNER JOIN CAROUSEL C ON M.CAROUSEL = C.CAROUSEL INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE WHERE D.CONNECTKEY = p_connectkey),
    FALSE,
    NOW()
);

END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UpdateDeviceLastPing`(IN p_connectkey VARCHAR(255))
BEGIN
    UPDATE DEVICE
    SET LASTPING = NOW()
    WHERE CONNECTKEY = p_connectkey;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UpdateRedeemed`(IN p_redeemcode INT)
BEGIN
UPDATE ISSUEDPROMO 
SET REDEEMED = 1, 
REDEEMDATE = NOW()
WHERE REDEEMCODE = p_redeemcode;
END$$
DELIMITER ;
