CREATE TABLE USER (
    USER        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USERNAME    VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD   	VARCHAR(255) NOT NULL
);

CREATE TABLE DEVICE (
    DEVICE      INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    CODE        VARCHAR(100) NOT NULL UNIQUE,            
    NAME 		VARCHAR(255), 
    
    LOCATION    VARCHAR(255),                            
    LASTPING 	DATETIME,
    URL			VARCHAR(255)
);

CREATE TABLE TYPE (
	TYPE 		INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	CODE 		INT UNSIGNED NOT NULL,
	NAME 		VARCHAR(255) NOT NULL
);

CREATE TABLE MAKER (
	MAKER 		INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	CODE 		INT UNSIGNED NOT NULL,
	NAME 		VARCHAR(255) NOT NULL
);

