DELIMITER $$

CREATE PROCEDURE GetMinigamePromos(IN p_carousel BOOLEAN)
BEGIN
    SELECT 
	CHANCE,
    PRO.CODE AS PROMOCODE,
    PRO.DISCOUNT,
    PRO.DAYSTOLIVE,
    T.CODE AS TYPECODE,
    T.NAME AS TYPENAME,
    M.CODE AS MAKERCODE,
    M.NAME AS TYPEMAKER,
    P.CODE AS PRODUCTCODE,
    P.NAME AS PRODUCTNAME,
    P.FINALPRICE AS PRODUCTPRICE    
FROM 
	MINIGAME MG
INNER JOIN 
	PROMOLINES PRL ON PRL.MINIGAME = MG.MINIGAME
INNER JOIN 
	PROMO PRO ON PRO.PROMO = PRL.PROMO
LEFT JOIN 
	PRODUCT P ON PRO.PRODUCT = P.PRODUCT
LEFT JOIN 
	MAKER M ON M.MAKER = PRO.MAKER
LEFT JOIN 
	TYPE T ON T.TYPE = PRO.TYPE
WHERE
	CAROUSEL = p_carousel;
END$$

DELIMITER ;
