DELIMITER //

CREATE PROCEDURE InsertProduct (
    IN p_CODE        INT,
    IN p_NAME        VARCHAR(255),
    IN p_TYPE        INT,
    IN p_MAKER       INT,
    IN p_PRICE       FLOAT,
    IN p_DISCOUNT    FLOAT,
    IN p_FINALPRICE  FLOAT,
    IN p_NOTES       VARCHAR(255)
)
BEGIN
    INSERT INTO PRODUCT (
        CODE, NAME, TYPE, MAKER, PRICE, DISCOUNT, FINALPRICE, NOTES
    ) VALUES (
        p_CODE, p_NAME, p_TYPE, p_MAKER, p_PRICE, p_DISCOUNT, p_FINALPRICE, p_NOTES
    );
END //

DELIMITER ;