DELIMITER //

CREATE PROCEDURE GetCarouselProductsCarousel (IN p_carousel VARCHAR(255))
BEGIN
	SELECT 
        PL.PRODUCT, 
        PL.QUEUE,
        PR.NAME,
        PR.PRICE,
        PR.DISCOUNT,
        PR.FINALPRICE
    FROM 
        PRODUCTLINES PL
	INNER JOIN 
		PRODUCT PR ON PL.PRODUCT = PR.PRODUCT
	INNER JOIN 
		CAROUSEL C ON C.CAROUSEL = PL.CAROUSEL
    WHERE 
        D.CONNECTKEY = p_connectkey
    ORDER BY 
        PL.QUEUE;
END //

DELIMITER ;
