SELECT T.NAME AS 'TYPE NAME',P.DISCOUNT,P.CHANCE,P.TOTAL AS 'GIVEN IN A DAY',C.NAME AS 'CAROUSEL NAME',D.LOCATION FROM PROMO P
INNER JOIN TYPE T ON P.TYPE = T.TYPE
INNER JOIN PROMOLINES L ON P.PROMO = L.PROMO
INNER JOIN WHEEL W ON W.WHEEL = L.WHEEL
INNER JOIN CAROUSEL C ON C.CAROUSEL = W.CAROUSEL
INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE;

SELECT M.NAME AS 'MAKER NAME',P.DISCOUNT,P.CHANCE,P.TOTAL AS 'GIVEN IN A DAY',C.NAME AS 'CAROUSEL NAME',D.LOCATION FROM PROMO P
INNER JOIN MAKER M ON P.MAKER = M.MAKER
INNER JOIN PROMOLINES L ON P.PROMO = L.PROMO
INNER JOIN WHEEL W ON W.WHEEL = L.WHEEL
INNER JOIN CAROUSEL C ON C.CAROUSEL = W.CAROUSEL
INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE;

SELECT M.NAME AS 'MAKER NAME',P.DISCOUNT,P.CHANCE,P.TOTAL AS 'GIVEN IN A DAY',C.NAME AS 'CAROUSEL NAME',D.LOCATION FROM PROMO P
INNER JOIN MAKER M ON P.MAKER = M.MAKER
INNER JOIN PROMOLINES L ON P.PROMO = L.PROMO
INNER JOIN WHEEL W ON W.WHEEL = L.WHEEL
INNER JOIN CAROUSEL C ON C.CAROUSEL = W.CAROUSEL
INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE;

SELECT PR.NAME AS 'MAKER NAME',P.DISCOUNT,P.CHANCE,P.TOTAL AS 'GIVEN IN A DAY',C.NAME AS 'CAROUSEL NAME',D.LOCATION FROM PROMO P
INNER JOIN PRODUCT PR ON PR.PRODUCT = P.PRODUCT
INNER JOIN PROMOLINES L ON P.PROMO = L.PROMO
INNER JOIN WHEEL W ON W.WHEEL = L.WHEEL
INNER JOIN CAROUSEL C ON C.CAROUSEL = W.CAROUSEL
INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE;

SELECT 
    T.NAME AS 'NAME SOURCE',
    'TYPE' AS 'SOURCE TYPE',
    P.CHANCE,
    P.TOTAL AS 'GIVEN IN A DAY',
    C.NAME AS 'CAROUSEL NAME',
    D.LOCATION
FROM PROMO P
INNER JOIN TYPE T ON P.TYPE = T.TYPE
INNER JOIN PROMOLINES L ON P.PROMO = L.PROMO
INNER JOIN WHEEL W ON W.WHEEL = L.WHEEL
INNER JOIN CAROUSEL C ON C.CAROUSEL = W.CAROUSEL
INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE

UNION ALL

SELECT 
    M.NAME AS 'NAME SOURCE',
    'MAKER' AS 'SOURCE TYPE',
    P.CHANCE,
    P.TOTAL AS 'GIVEN IN A DAY',
    C.NAME AS 'CAROUSEL NAME',
    D.LOCATION
FROM PROMO P
INNER JOIN MAKER M ON P.MAKER = M.MAKER
INNER JOIN PROMOLINES L ON P.PROMO = L.PROMO
INNER JOIN WHEEL W ON W.WHEEL = L.WHEEL
INNER JOIN CAROUSEL C ON C.CAROUSEL = W.CAROUSEL
INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE

UNION ALL

SELECT 
    PR.NAME AS 'NAME SOURCE',
    'PRODUCT' AS 'SOURCE TYPE',
    P.CHANCE,
    P.TOTAL AS 'GIVEN IN A DAY',
    C.NAME AS 'CAROUSEL NAME',
    D.LOCATION
FROM PROMO P
INNER JOIN PRODUCT PR ON PR.PRODUCT = P.PRODUCT
INNER JOIN PROMOLINES L ON P.PROMO = L.PROMO
INNER JOIN WHEEL W ON W.WHEEL = L.WHEEL
INNER JOIN CAROUSEL C ON C.CAROUSEL = W.CAROUSEL
INNER JOIN DEVICE D ON D.DEVICE = C.DEVICE;

SELECT * FROM ISSUEDPROMO I
INNER JOIN PROMO P ON P.PROMO = I.PROMO;
    
