CREATE TABLE IF NOT EXISTS USER (
    USER        INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME    VARCHAR(255) NOT NULL,
    PASSWORD   	VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEVICE (
    DEVICE      INT AUTO_INCREMENT PRIMARY KEY, 
    CODE        INT,            
    NAME 		VARCHAR(255), 
    
    LASTPING 	DATETIME,
    CONNECTKEY	VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TYPE (
	TYPE 		INT AUTO_INCREMENT PRIMARY KEY,
	CODE 		INT,
	NAME 		VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MAKER (
	MAKER 		INT AUTO_INCREMENT PRIMARY KEY,
	CODE 		INT,
	NAME 		VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT (
	PRODUCT 	INT AUTO_INCREMENT PRIMARY KEY,
    CODE 		INT UNIQUE,
    NAME		VARCHAR(255) NOT NULL,
    
    TYPE		INT NOT NULL,
    MAKER		INT NOT NULL,
    PRICE 		FLOAT,
    DISCOUNT 	FLOAT,
    FINALPRICE	FLOAT,
    NOTES 		VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CAROUSEL (
	CAROUSEL 		INT AUTO_INCREMENT PRIMARY KEY,
    CODE 			INT,
    NAME			VARCHAR(255) NOT NULL,
    
    DEVICE			INT,
    AUTOPLAYWAIT 	INT,
    SPEED	 		INT,
    GAMECOUNT		INT,
    STATE 			INT
);

CREATE TABLE IF NOT EXISTS PROMO (
	PROMO	 	INT AUTO_INCREMENT PRIMARY KEY,
    CODE 		INT,
    
    PRODUCT		INT,
    TYPE		INT,
    MAKER		INT,
    NOTES 		VARCHAR(255),
    
    DISCOUNT	FLOAT,
    DAYSTOLIVE	INT
);

CREATE TABLE IF NOT EXISTS MINIGAME (
	MINIGAME 		INT AUTO_INCREMENT PRIMARY KEY,
    CAROUSEL		INT NOT NULL,
    
    REVOLUTIONS		INT,
    SPINDURATION 	INT,
    ONSTOPTIME		INT,
    INACTIVITYTIME 	INT
);

CREATE TABLE IF NOT EXISTS PRODUCTLINES (
	PRODUCTLINES 	INT AUTO_INCREMENT PRIMARY KEY,
    CAROUSEL		INT NOT NULL,
    PRODUCT			INT NOT NULL,
    QUEUE 			INT
);

CREATE TABLE IF NOT EXISTS BACKSWIPES (
	BACKSWIPES 		INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTLINES	INT NOT NULL,
    SWIPEDATE		DATETIME
);

CREATE TABLE IF NOT EXISTS PROMOLINES (
	PROMOLINES 		INT AUTO_INCREMENT PRIMARY KEY,
    PROMO			INT NOT NULL,
    MINIGAME		INT NOT NULL,
	CHANCE	 		FLOAT
);

CREATE TABLE IF NOT EXISTS ISSUEDPROMO (
	ISSUEDPROMO	INT AUTO_INCREMENT PRIMARY KEY,
    
    REDEEMCODE 	INT NOT NULL,
    PROMO		INT NOT NULL,
    DEVICE		INT,
    CAROUSEL	INT,
    MINIGAME	INT,
    REDEEMED	BOOLEAN,
    ISSUEDATE	DATETIME,
    REDEEMDATE 	DATETIME
);


